#!/usr/bin/env node
// Generated by LiveScript 1.6.0
(function(){
  var decode, fs, chroma, args, twidth, ref$, data, width, rgbaArr, res$, i$, to$, i, lresult$, j$, i2, imgchars, chars, key, rgba, char, line;
  decode = require("image-decode");
  fs = require('fs');
  chroma = require('chroma');
  args = process.argv.slice(2);
  twidth = process.stdout.rows;
  ref$ = decode(fs.readFileSync(__dirname + "/kogasa.png")), data = ref$.data, width = ref$.width;
  res$ = [];
  for (i$ = 0, to$ = data.length / 4; i$ <= to$; ++i$) {
    i = i$;
    lresult$ = [];
    for (j$ = 0; j$ <= 3; ++j$) {
      i2 = j$;
      lresult$.push(data[i * 4 + i2]);
    }
    res$.push(lresult$);
  }
  rgbaArr = res$;
  imgchars = [];
  chars = [];
  chars.push(chroma.magenta("TataraKogasa").split("").concat(chroma.red("@Gensokyo : ").split("")));
  for (key in rgbaArr) {
    rgba = rgbaArr[key];
    if (key % width === 0) {
      imgchars.push([]);
    }
    imgchars[imgchars.length - 1].push(rgba[3] !== 0 ? chroma.apply(this, rgba.slice(0, -1))("#") : " ");
  }
  imgchars = imgchars.slice(0, -1);
  for (key in ref$ = args.join(" ")) {
    char = ref$[key];
    if (key % twidth === 0) {
      chars.push([]);
      chars[chars.length - 1].push(char);
    } else if (char === "\n") {
      chars.push([]);
    } else {
      chars[chars.length - 1].push(char);
    }
  }
  if (imgchars.length >= chars.length) {
    for (key in imgchars) {
      line = imgchars[key];
      console.log(line.join("") + (" " + key.padStart(2, "0") + "| ") + chroma.white((chars[key] || []).join("")));
    }
  } else {
    for (key in chars) {
      line = chars[key];
      console.log(line.join("") + (" " + key.padStart(2, "0") + "| ") + chroma.white((imgchars[key] || []).join("")));
    }
  }
}).call(this);
